jka_41chapter_screen（なおき）
yukihiroLaravel/laravel_next_docker pull request #3
Opened 2022-10-18 13:46 UTC by Kaneko0000

## issue
- chapter画面API

## やったこと
- チャプター画面に必要なAPIの定義

## 考慮して欲しいこと
- 定義のみです。

2022-10-18 22:50 UTC, Hikaru-Giannis commented on api/openapi.yaml
> +                  $ref: '#/components/schemas/Chapter'
この記述は、paths:の下に記述する必要があります。
- 今回はチャプター一覧情報を取得するAPIですので、パスを変えましょう！ /v1/~
- tagsはそのままで問題ないです。
- 受講者IDのパラメーターだけで、果たしてチャプター一覧情報を取得できますでしょうか？
- 認証トークンは問題ないです！
- `reponses:` はどんなデータが返ってくるかを定義する場所です！
 - 以前の画面定義書で決めたデータをどのようにして渡すか考えてみましょう。
 - schemaを使ってもいいですが、使い方わからない場合は、オブジェクトと配列を指定しての定義でも問題ないです！

2022-10-20 04:24 UTC, Kaneko0000 commented on api/openapi.yaml
> +                  $ref: '#/components/schemas/Chapter'
ouさんと同じ書き方で、配列形式で書いてみました。
Statusの書き方がわかりませんでした。未・済のような書き方でいいんでしょうか？
あと、Exampleでサンプルを表示させているということですか？

2022-10-20 11:46 UTC, Hikaru-Giannis commented on api/openapi.yaml
> +                  $ref: '#/components/schemas/Chapter'
- statusは受講状態を表すので、未着手、着手中、完了だと思います。
- Exampleはサンプルデータを表示しているという認識で問題ないです！

2022-10-20 11:53 UTC, Hikaru-Giannis reviewed
全体レビュー
段々と良くなってきいますね。
以下現状のレビュー内容です！
- 講座情報を表示できなくないでしょうか？ -> 講座情報がなさそう。
- レッスンも配列にしないと複数設定できず、１つのレッスン情報しか取得できないかと思います！

2022-10-20 13:56 UTC, Kaneko0000 commented on api/openapi.yaml
> +                  $ref: '#/components/schemas/Chapter'
・statusは受講状態を表すのでdescriptionは説明ですので、未着手、着手中、完了だと思います。
　←  "未or済" から "未着手、着手、完了"　に変更しました。
・statusのマスタ値は現状の設定値で問題ないです！(10, 20, 30)とかでも良いかもしれません。
　← typeをtinyintに変更しておきました。こちらのほうがよかったですよね？
講座情報を表示できなくないでしょうか？ -> 講座情報がなさそう。
　← そうでした。courseを加えました。
レッスンも配列にしないと複数設定できず、１つのレッスン情報しか取得できないかと思います！
　← これがよくわからないです。ある講座の中のチャプターと言うことなので、講座のなかにlessonを入れるということでしょうか？と言うことだと考えていれる方法をあれこれしてますが、できません。
jsonエディター貼っていただいたもの、今みたので明日やってみたいと思います。

2022-10-23 10:54 UTC, Hikaru-Giannis commented on api/openapi.yaml
> +    Chapter_lesson:
Shemaの形はアッパーキャメルケースでお願いします！
今回の場合でいうと、ChapterLessonといった感じでお願いしますー。

2022-10-23 10:54 UTC, Hikaru-Giannis commented on api/openapi.yaml
> +          $ref: '#/components/schemas/chapter>lesson'
コース詳細なので、ChpterではなくCourseで良い気がします！
あと、チャプターの情報足りなくないでしょうか？

2022-10-23 11:07 UTC, Kaneko0000 commented on api/openapi.yaml
> +          in: quy
間違えていたようですね。訂正しておきました！

2022-10-23 11:20 UTC, Kaneko0000 commented on api/openapi.yaml
> +    get:
チャプター一覧の画面は講座あってのページということで、
paths:は「/v1/course:」に変えておきました。

2022-10-23 11:31 UTC, Kaneko0000 commented on api/openapi.yaml
> +    Chapter_lesson:
アッパーキャメルケースに変更しておきました。
Chapter_lesson → ChapterLesson　に修正

2022-10-23 11:33 UTC, Kaneko0000 commented on api/openapi.yaml
> +          $ref: '#/components/schemas/chapter>lesson'
チャプターのtitleが足りませんでした！
title追加してます。

2022-10-24 23:38 UTC, Hikaru-Giannis reviewed
コメントを残しました！

2022-10-24 23:38 UTC, Hikaru-Giannis commented on api/openapi.yaml
> +                  $ref: '#/components/schemas/ChapterLesson'
この部分私もやっているのですが、配列のデータをフロント側で取り出すのは大変なので、下記のように修正した方が良いかもしれないです！なおきさんの方で修正していただいて、せきさんに確認していただいてもよろしいでしょうか？
その回答によっては、お手数をおかけしますが、私のAPIの方も修正していただければと思います！

````
   type: object
                properties:
                  data:
````

2022-10-24 23:38 UTC, Hikaru-Giannis commented on api/openapi.yaml
> +          description: "未着手、着手、完了"
statusはtinyintなので数字が入りますね！

2022-10-25 01:17 UTC, Kaneko0000 commented on api/openapi.yaml
> +                  $ref: '#/components/schemas/ChapterLesson'
type: arrayの前に type: objectを挟むということですね。
了解しました！
ユキヒロさんにその旨伝えておきます。

2022-10-25 01:19 UTC, Kaneko0000 commented on api/openapi.yaml
> +          description: "未着手、着手、完了"
description: ”10, 20, 30”
といった書き方であってますか？？
そのように書いておきます！

2022-10-25 23:37 UTC, Hikaru-Giannis approved these changes
問題ないと思われますので、LGTMです。
お疲れ様でした！

2022-10-26 01:36 UTC, yukihiroLaravel requested changes
いくつかコメントしましたので
お手数ですがご確認願います☺️

2022-10-26 01:36 UTC, yukihiroLaravel commented on api/openapi.yaml
> +  /v1/course:
/v1/chapters などではないでしょうか？

2022-10-26 01:36 UTC, yukihiroLaravel commented on api/openapi.yaml
> +        - name: attendances_id
attendance_id
と単数形ではないでしょうか？

2022-10-26 01:36 UTC, yukihiroLaravel commented on api/openapi.yaml
> +          example: "未着手"
ここに入るのは「未着手」という文字列ではなく整数だと思います！

2022-10-26 02:00 UTC, Kaneko0000 commented on api/openapi.yaml
> +        - name: attendances_id
そうでした！訂正しました。

2022-10-26 02:00 UTC, Kaneko0000 commented on api/openapi.yaml
> +          example: "未着手"
訂正しておきました！

2022-10-26 05:45 UTC, yukihiroLaravel requested changes
またお手数ですが追加でコメントしました！
ご確認ください！

2022-10-26 05:45 UTC, yukihiroLaravel commented on api/openapi.yaml
> +          description: "10, 20, 30"
descriptionは上の通りあくまで日本語での説明なので、Kouさんの書かれているのは
`description: "レッスン受講状態（未着手, 着手, 完了）"`
こういうことだと思います！

2022-10-26 05:45 UTC, yukihiroLaravel commented on api/openapi.yaml
> +  /v1/course:
そういう意図ならこのままでOKです！

2022-10-26 06:04 UTC, Kaneko0000 commented on api/openapi.yaml
> +          description: "10, 20, 30"
example: "10"だったと言うことですね。
訂正しておきました！

2022-10-26 09:34 UTC, merged